net: core: fix UID-based routing build
Use kuid_t GLOBAL_ROOT_UID instead of "0"
otherwise we run into following build failure:

include/net/route.h: In function 'ip_route_output_ports':
include/net/route.h:143:55: error: type mismatch in conditional expression
       daddr, saddr, dport, sport, sk ? sock_i_uid(sk) : 0);
                                                       ^

Signed-off-by: Amit Pundir <amit.pundir@linaro.org>